export const CHANGE_FIELD_VALUE = 'CHANGE_FIELD_VALUE';
export const CREATE_FIELD = 'CREATE_FIELD';
export const REQUEST_REGISTER_FIELDS = 'REQUEST_REGISTER_FIELDS';
export const RECIEVE_REGISTER_FIELDS = 'RECIEVE_REGISTER_FIELDS';
