export const CHANGE_FIELD_VALUE = 'CHANGE_FIELD_VALUE';
export const CREATE_FIELD = 'CREATE_FIELD';

// REGISTER ACTIONS
export const REQUEST_REGISTER_FIELDS = 'REQUEST_REGISTER_FIELDS';
export const RECIEVE_REGISTER_FIELDS = 'RECIEVE_REGISTER_FIELDS';
export const HANDLE_REGISTER_FIELD_CHANGE = 'HANDLE_REGISTER_FIELD_CHANGE';
export const ADD_REGISTER_ERROR = 'ADD_REGISTER_ERROR';
export const DOING_REGISTER_SUBMITION = 'DOING_REGISTER_SUBMITION';
export const DID_REGISTER_WITH_SUCCESS = 'DID_REGISTER_WITH_SUCCESS';
export const DID_REGISTER_WITH_ERROR = 'DID_REGISTER_WITH_ERROR';
export const DID_REGISTER_SYSTEM_FAILURE = 'DID_REGISTER_SYSTEM_FAILURE';

// LOGIN ACTIONS
export const DOING_LOGIN = 'DOING_LOGIN';
export const DID_LOGIN_WITH_SUCCESS = 'DID_LOGIN_WITH_SUCCESS';
export const DID_LOGIN_WITH_ERROR = 'DID_LOGIN_WITH_ERROR';
export const DID_LOGIN_WITH_FAILURE = 'DID_LOGIN_WITH_FAILURE';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const HANDLE_LOGIN_FIELD_CHANGE = 'HANDLE_LOGIN_FIELD_CHANGE';
export const CLEAR_USER_LOGIN_DATA = 'CLEAR_USER_LOGIN_DATA';

// USER SESSION ACTIONS
export const SET_USER_SESSION_TOKEN = 'SET_USER_SESSION_TOKEN';
export const SET_USER_SESSION_DATA = 'SET_USER_DATA';
export const UPDATE_USER_SESSION_USER = 'UPDATE_USER_SESSION_USER';
export const CLEAR_USER_SESSION_DATA = 'CLEAR_USER_SESSION_DATA';

// EVENT PAGE ACTIONS
export const EVENT_PAGE_NOT_FOUND = 'EVENT_PAGE_NOT_FOUND';
export const SET_EVENT_PAGE_DATA = 'SET_EVENT_PAGE_DATA';
export const EVENT_PAGE_LOADED = 'EVENT_PAGE_LOADED';
export const SET_EVENT_ROLES = 'SET_EVENT_ROLES';
export const SET_EVENT_RELATIONSHIP = 'SET_EVENT_RELATIONSHIP';

// EVENT BOARD ACTIONS
export const SET_EVENTS_BOARD_CONTENT = 'SET_EVENTS_BOARD_CONTENT';
export const DID_LOAD_EVENTS_BOARD_WITH_ERROR = 'DID_LOAD_EVENTS_BOARD_WITH_ERROR';
export const SET_EVENT_CONTEXT = 'SET_EVENT_CONTEXT';

// PAYMENT ACTIONS
export const DOING_PAYMENT_RECEIPT_SUBMIT = 'DOING_PAYMENT_RECEIPT_SUBMIT';
export const DID_PAYMENT_RECEIPT_SUBMIT_WITH_SUCCESS = 'DID_PAYMENT_RECEIPT_SUBMIT_WITH_SUCCESS';
export const DID_PAYMENT_RECEIPT_SUBMIT_WITH_FAILURE = 'DID_PAYMENT_RECEIPT_SUBMIT_WITH_FAILURE';
export const SET_PAYMENT_INFO_DATA = 'SET_PAYMENT_INFO_DATA';
export const SET_PAYMENT_EXEMPTS_LIST = 'SET_PAYMENT_EXEMPTS_LIST';

export const SET_TO_APPROVE_PAYMENT_DATA = 'SET_TO_APPROVE_PAYMENT_DATA';

// THEMATIC GROUPS AREAS ACTIONS
export const SET_TGS_AREAS_AREAS = 'SET_TGS_AREAS_AREAS';

// THEMATIC GROUPS ACTIONS
export const SET_TGS_TGS = 'SET_TGS_TGS';

// SUBMISSION MODULE ACTIONS
export const SET_SUBMISSION_ENTITY = 'SET_SUBMISSION_ENTITY';
export const SET_SUBMISSION_USER_OBJECTS = 'SET_SUBMISSION_USER_OBJECTS';
export const SET_SUBMISSION_TO_APPROVE = 'SET_SUBMISSION_TO_APPROVE';
export const APPROVE_SUBMISSION = 'APPROVE_SUBMISSION';
export const REJECT_SUBMISSION = 'REJECT_SUBMISSION';

// NEWS MODULE ACTIONS
export const SET_SET_OF_NEWS = 'SET_SET_OF_NEWS';

// ACTIVITIES MODULE ACTIONS
export const SET_ACTIVITIES_ENTITY = 'SET_ACTIVITIES_ENTITY';
