export const CHANGE_FIELD_VALUE = 'CHANGE_FIELD_VALUE';
export const CREATE_FIELD = 'CREATE_FIELD';

// REGISTER ACTIONS
export const REQUEST_REGISTER_FIELDS = 'REQUEST_REGISTER_FIELDS';
export const RECIEVE_REGISTER_FIELDS = 'RECIEVE_REGISTER_FIELDS';
export const HANDLE_REGISTER_FIELD_CHANGE = 'HANDLE_REGISTER_FIELD_CHANGE';
export const ADD_REGISTER_ERROR = 'ADD_REGISTER_ERROR';
export const DOING_REGISTER_SUBMITION = 'DOING_REGISTER_SUBMITION';
export const DID_REGISTER_WITH_SUCCESS = 'DID_REGISTER_WITH_SUCCESS';
export const DID_REGISTER_WITH_ERROR = 'DID_REGISTER_WITH_ERROR';
export const DID_REGISTER_SYSTEM_FAILURE = 'DID_REGISTER_SYSTEM_FAILURE';
